codecov:
  require_ci_to_pass: true
comment:
  require_changes: false
coverage:
  precision: 2
  round: down
  range: 60.0..100.0
  status:
    project:
      default:
        target: 80.0%
        threshold: 1.0%
